/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc725 from "./@erc725";
export type { erc725 };
import type * as lukso from "./@lukso";
export type { lukso };
export * as factories from "./factories";
export type { ERC725Y } from "./@erc725/smart-contracts/artifacts/ERC725Y";
export { ERC725Y__factory } from "./factories/@erc725/smart-contracts/artifacts/ERC725Y__factory";
export type { UniversalProfile } from "./@lukso/lsp-smart-contracts/artifacts/UniversalProfile";
export { UniversalProfile__factory } from "./factories/@lukso/lsp-smart-contracts/artifacts/UniversalProfile__factory";
