/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC725Y } from "./ERC725Y";
export * as factories from "./factories";
export { ERC725Y__factory } from "./factories/ERC725Y__factory";
